#This is the main idea of this yaml file.
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '.'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hyrule-development-api-test:latest'

