apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorian-lapi
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: dorian-lapi
  template:
    metadata:
      labels:
        app: dorian-lapi
    spec:
      containers:
      - name: dorian-lapi
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
<<<<<<< HEAD
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
=======
            memory: 250m
          requests:
            cpu: 50m
            memory: 100m
>>>>>>> ea6d1caaaf3d66a850649975c606da764b5f2f7a
            #commentt
           


