apiVersion: apps/v1
kind: Deployment
metadata:
  name: joshua-petersen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joshua-petersen
  template:
    metadata:
      labels:
        app: joshua-petersen
    spec:
      containers:
      - name: joshua-petersen
        image: nginx
        ports: 
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
